### ISSUE TITLE
Recording Time: UTC vs Local Time 

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/adrift-analysis-methods#1]
@TaikiSan21 What is the script that checks this? 

@chomweaver I know you had to fix the times/names for Pascal, what are the steps to do that? 

https://github.com/SAEL-SWFSC/adrift-analysis-methods/blob/848cfdc58d76d78c62f090ea4b65737aae7e792b/content/Data%20Archive/DataQualityCheck.qmd#L10-L14

**Comment by TaikiSan21** [comment]
I want to rework the script a bit for this, I'll upload it to the PAMmisc GitHub when I'm done. 

For the PASCAL data, I can't remember if we ever actually renamed the files (Cory probably knows better than I do), but I do have the list of time corrections that need to happen. PASCAL Stations 2, 3, 4, 5, 6, 9, 12, 15, 16, 26, 27, 28, 29, 30 the original files were in local time, so they need 7 hours added to get adjusted to UTC. PASCAL Station 1 I have no idea what happened, but it needs 10.8 (yes, 10.8) hours added to adjust to UTC. These numbers are from what Jay did in an analysis using the PASCAL data.

The script I have uses the Soundtrap log files to check what timezone each file is in, then corrects to UTC if it was something other than UTC. If we don't have the log files, but you know what correction should be applied, then you can just tell it how many hours to add or subtract. I believe that's what we did for PASCAL because we couldn't find the log files, but I'll let Cory confirm

**Comment by chomweaverNOAA** [comment]
Yes that is what we did for PASCAL. For some of the Drifts there were no log files so we ended up just using the 7 hour offset. All of those recordings are currently on PAM2 but I will transfer them to the DON soon

**Comment by Kourtney-Burger** [comment]
@TaikiSan21 Just following up, do you have the updated script for checking UTC vs local time?

**Comment by TaikiSan21** [comment]
Yes, functions are [here](https://github.com/TaikiSan21/PAMmisc/blob/main/devel/soundtrapRenamer.R) and script example to run it is [here](https://github.com/TaikiSan21/PAMmisc/blob/main/devel/NewRenameScript.R). It checks the log files and does the renaming for you and creates a log file in that folder of changes it made. There is also a `reverse` option that you can set to `TRUE` if you want to undo the renaming that it did.

**Comment by Kourtney-Burger** [comment]
Sorry Taiki, I didn't even connect the dots that the renamer script includes the time zone check. Thanks for reminding me! 

I spoke with Shannon about running the time zone check function before any other data prep is done (including renaming if that needs to be done). Can I run getStTz as an independent function to check if a drift was off loaded in the correct time zone? Or does the soundtrapRenamer need to be run as a whole?

**Comment by TaikiSan21** [comment]
You run `prepTzFix` first, and that will tell you if there are non-UTC files present based on the log files. This is the input to the function that actually changes the names, so you will always be able to see if there are files that need to be changed before you run `fixStTz` which actually does the changing of names.

**Comment by Kourtney-Burger** [comment]
Ok perfect, I will try that and let you know if I need anything else. Thanks!
